"use client"

import { useEffect, useState, useReducer } from 'react';

import useDefaultWebsocket from '@/lib/websocket';

import localFont from "next/font/local";
import "@/styles/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Sidebar from "@/components/sidebar";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

import { Bounce, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({ children }) {

    const {sendJsonMessage, lastJsonMessage, readyState} = useDefaultWebsocket()

    useEffect(() => {
        let op = lastJsonMessage?.op
        let ws_data = lastJsonMessage?.data
        if (!op || !lastJsonMessage.path) return

        if (op === "ping") {
            sendJsonMessage({
                "op": "pong"
            })
        }
    }, [lastJsonMessage])

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Header />
            <div>
            <Sidebar />
            <main>
                {children}
            </main>
            </div>
            <ToastContainer   
                position="bottom-right"
                autoClose={2000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss={false}
                draggable={false}
                pauseOnHover
                theme="light"
                transition={Bounce}
            />
            <Footer />
        </body>
        </html>
    );
}
